<?php

namespace App\Controllers\Automation;

use App\Controllers\BaseController;
use App\Services\CycleAutomationService;
use RuntimeException;

class CycleGeneratorController extends BaseController
{
    private CycleAutomationService $automation;

    public function __construct()
    {
        $this->automation = new CycleAutomationService();
    }

    public function index()
    {
        if (! $this->isAllowed()) {
            return redirect()->to('/dashboard')->with('error', 'Only Super User or Admin can use cycle automation.');
        }

        return view('automation/cycle_form', [
            'title' => 'Automation / Cycle Generator',
            'pageTitle' => 'Automation / Cycle Generator',
            'pageSubtitle' => 'Create a full certification cycle from basic client information',
            'standards' => $this->automation->standards(),
            'iafCodes' => $this->automation->iafCodes(),
            'foodCategories' => $this->automation->foodCategories(),
            'medicalCategories' => $this->automation->medicalCategories(),
            'input' => [],
        ]);
    }

    public function preview()
    {
        if (! $this->isAllowed()) {
            return redirect()->to('/dashboard')->with('error', 'Only Super User or Admin can use cycle automation.');
        }

        try {
            $preview = $this->automation->preview(
                $this->request->getPost(),
                (int) session()->get('tenant_id'),
                (int) session()->get('user_id')
            );
        } catch (RuntimeException $exception) {
            return redirect()->back()->withInput()->with('error', $exception->getMessage());
        }

        return view('automation/cycle_preview', [
            'title' => 'Cycle Preview',
            'pageTitle' => 'Cycle Preview',
            'pageSubtitle' => $preview['input']['client_name'],
            'preview' => $preview,
            'encodedPreview' => base64_encode(json_encode($preview, JSON_THROW_ON_ERROR)),
        ]);
    }

    public function generate()
    {
        if (! $this->isAllowed()) {
            return redirect()->to('/dashboard')->with('error', 'Only Super User or Admin can use cycle automation.');
        }

        $encoded = (string) $this->request->getPost('preview_payload');
        $preview = json_decode(base64_decode($encoded, true) ?: '', true);
        if (! is_array($preview)) {
            return redirect()->to('/automation/cycle-generator')->with('error', 'Preview payload expired or invalid. Please preview again.');
        }

        try {
            $result = $this->automation->generate(
                $preview,
                (int) session()->get('tenant_id'),
                (int) session()->get('user_id')
            );
        } catch (RuntimeException $exception) {
            return redirect()->to('/automation/cycle-generator')->with('error', $exception->getMessage());
        }

        return redirect()
            ->to('/workflow/certification/' . $result['client_id'])
            ->with('success', 'Full certification cycle generated by automation.');
    }

    private function isAllowed(): bool
    {
        $roles = (array) session()->get('role_codes');

        return in_array('super_admin', $roles, true) || in_array('administrator', $roles, true);
    }
}
