<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class UpdateControlledTemplateFooterLanguage extends Migration
{
    public function up()
    {
        if ($this->db->tableExists('document_template_versions')) {
            $this->db->table('document_template_versions')
                ->like('footer_html', 'Controlled document generated by QSI AMS')
                ->update(['footer_html' => '<div>Controlled document prepared by QSI AMS</div>']);
        }
    }

    public function down()
    {
        if ($this->db->tableExists('document_template_versions')) {
            $this->db->table('document_template_versions')
                ->like('footer_html', 'Controlled document prepared by QSI AMS')
                ->update(['footer_html' => '<div>Controlled document generated by QSI AMS</div>']);
        }
    }
}
